### ISSUE TITLE
Example angular project needed to understand the test clearly

### ISSUE THREAD

**Issue by tusharjoshi** [csupnig/tjangular#1]
There are many areas where the usage of this library is not clear, instead of documenting each unclear area I suggest adding a small angular example project which can be taken as starting point of implementing this library.

The example given in the documentation does not show other imports and actual angular components which are tested, hence makes this only theory example.

Please add an angular example project.

**Comment by csupnig** [comment]
Thank you for the request. The projects I used this on so far, are unfortunately private company code. I will put together a sample project as soon as I can find some time.

**Comment by tusharjoshi** [comment]
Thanks for the response, for one of my workshops, @here https://github.com/tusharvjoshi/angular1.5-protractor-concepts where I wanted to demonstrate Angular 1.5 with TypeScript decorators, I though of using this project for Jasmine 
I used ngMetadata for other decorators and needed the example to fit into my workshop examples, but was not sure how to use these decorators for that project.  An example will really help me use these decorators with that workshop project.
